server:
  port: 8080
spring:
  data:
    mongodb:
      database: book_storage
      host: localhost
      port: 27017
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.book_storage.changelogs
de:
  flapp